Repository KinsonDigital/CICD, pull requests merged in 2022-10, with the labels that each got.

#56 🚧Review and fix documentation
  CICD/Enums.cs
  CICD/ExtensionMethods.cs
  CICD/Factories/ServiceFactory.cs
  CICD/Guards/EnsureThat.cs
  CICD/Services/GitHubActionsService.cs
  CICD/Services/IExecutionContextService.cs
  CICD/Services/IGitHubActionsService.cs
  CICD/Services/IGitHubTokenService.cs
  CICD/Services/IWorkflowService.cs
  CICD/Services/NugetDataService.cs
  Documentation/Branching.md
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.4.md
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.5.md
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.6.md
  Testing/CICDTests/Helpers/AssertExtensions.cs
  Testing/CICDTests/Services/GitHubActionsServiceTests.cs
  Testing/CICDTests/Services/GitHubClientServiceTests.cs
Labels: good first issue, medium priority, preview, 📝documentation/product

#62 🚧Move internal visible setup
  CICD/App.cs
  CICD/CICD.csproj
  Testing/CICDTests/Services/GitHubActionsServiceTests.cs
Labels: low priority, preview, tech debt

#68 🚧Issue with detecting open milestone pull requests
  .nuke/parameters.json
  CICD/CICD.Common.cs
  CICD/CICD.Release.Preview.cs
  CICD/CICD.Release.Production.cs
  CICD/CICD.Requirements.cs
  CICD/CICD.StatusChecks.cs
Labels: high priority, preview, 🐛bug

#70 🚧Non existing nuget not handled correctly
  CICD.sln.DotSettings
  CICD/CICD.Common.cs
  CICD/CICD.Requirements.cs
  CICD/Enums.cs
Labels: high priority, preview, 🐛bug

#72 🚧Add target to show current version
  .nuke/build.schema.json
  CICD/CICD.Common.cs
Labels: low priority, preview, ✨new feature

#73 🚧Create unit tests for extension methods
  CICD/ExtensionMethods.cs
  Testing/CICDTests/ExtensionMethodsTests.cs
Labels: low priority, preview, tech debt

#82 🚧Exception thrown for preview releases
  CICD/CICD.cs
Labels: high priority, preview, 🐛bug

#83 🚧Fix simple logging issue
  CICD/CICD.Requirements.cs
Labels: low priority, preview, tech debt, 📝documentation/product

#84 🚧Adjust logging of requirement method
  CICD/CICD.Requirements.cs
Labels: low priority, preview, tech debt, 📝documentation/product

#85 🚧Check for milestone in PR status checks
  CICD/CICD.Requirements.cs
  CICD/CICD.StatusChecks.cs
  CICD/ExtensionMethods.cs
Labels: medium priority, preview, ✨new feature

#87 🚧Fix issue with creating milestone description
  CICD.sln.DotSettings
  CICD/CICD.Common.cs
  CICD/CICD.Release.Preview.cs
  CICD/CICD.Release.Production.cs
  CICD/ExtensionMethods.cs
Labels: high priority, preview, 🐛bug

#89 🚀Preview Release
  CICD.sln.DotSettings
  CICD/CICD.Common.cs
  CICD/CICD.Release.Preview.cs
  CICD/CICD.Release.Production.cs
  CICD/CICD.Requirements.cs
  CICD/CICD.StatusChecks.cs
  CICD/CICD.cs
  CICD/CICD.csproj
  CICD/ExtensionMethods.cs
  Documentation/ReleaseNotes/Preview-Release-Notes-TEMPLATE.md
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.10.md
Labels: 🚀Preview Release

#97 🚧Fix requirement issue with hotfix pr status checks
  CICD/CICD.Common.cs
  CICD/CICD.Requirements.cs
  CICD/CICD.StatusChecks.cs
Labels: high priority, preview, 🐛bug

#99 🚧Fix release note title logging issue
  CICD/CICD.Requirements.cs
Labels: low priority, preview, 📝documentation/product

#101 🚧Simple logging adjustment
  CICD/CICD.Requirements.cs
Labels: low priority, preview, 📝documentation/product

#102 🚧Change milestone description
  CICD/CICD.Common.cs
Labels: low priority, preview, 📝documentation/product

#103 🚧Fix logging issue with milestone assignment check
  CICD/CICD.Requirements.cs
Labels: low priority, preview, 📝documentation/product

#98 🚧Requirements added to hotfix pr status check target
  .nuke/parameters.json
  CICD/CICD.Release.Preview.cs
  CICD/CICD.Release.Production.cs
  CICD/CICD.Requirements.cs
  CICD/CICD.StatusChecks.cs
  CICD/ExtensionMethods.cs
Labels: high priority, preview, ✨new feature

#114 🚧Release PR status checks not working correctly
  CICD/ExtensionMethods.cs
Labels: high priority, preview, 🐛bug

#116 🚀Preview Release
  CICD/CICD.csproj
  CICD/ExtensionMethods.cs
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.11.md
  Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.12.md
Labels: 🚀Preview Release
